# Generated by Django 4.2.2 on 2023-11-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectores_gubernamentales', '0001_initial'),
        ('formularios_sectoriales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariosectorial',
            name='usuario',
        ),
        migrations.AddField(
            model_name='formulariosectorial',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='formularios_sectoriales', to='sectores_gubernamentales.sectorgubernamental'),
            preserve_default=False,
        ),
    ]
