# Generated by Django 4.2.2 on 2023-11-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0003_competencia_plazo_formulario_gore_and_more'),
        ('formularios_sectoriales', '0002_remove_formulariosectorial_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariosectorial',
            name='etapa',
        ),
        migrations.AddField(
            model_name='formulariosectorial',
            name='competencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia'),
            preserve_default=False,
        ),
    ]
