# Generated by Django 4.2.2 on 2023-11-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0003_remove_formulariosectorial_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariosectorial',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
