# Generated by Django 4.2.2 on 2023-12-05 23:39

import applications.base.functions
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regioncomuna', '0002_auto_20231103_1736'),
        ('formularios_sectoriales', '0005_alter_formulariosectorial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('completada', models.BooleanField(default=False)),
                ('forma_juridica_organismo', models.TextField(blank=True, max_length=500)),
                ('descripcion_archivo_marco_juridico', models.TextField(blank=True, max_length=500)),
                ('mision_institucional', models.TextField(blank=True, max_length=500)),
                ('informacion_adicional_marco_juridico', models.TextField(blank=True, max_length=500)),
                ('organigrama_nacional', models.FileField(blank=True, null=True, upload_to='formulario_sectorial', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Organigrama Nacional')),
                ('descripcion_archivo_organigrama_regional', models.TextField(blank=True, max_length=500)),
                ('identificacion_competencia', models.TextField(blank=True, max_length=500)),
                ('fuentes_normativas', models.TextField(blank=True, max_length=500)),
                ('territorio_competencia', models.TextField(blank=True, max_length=500)),
                ('enfoque_territorial_competencia', models.TextField(blank=True, max_length=500)),
                ('ambito', models.CharField(blank=True, choices=[('AP', 'Fomento de las Actividades Productivas'), ('OT', 'Ordenamiento Territorial'), ('DSC', 'Desarrollo Social y Cultural')], max_length=5)),
                ('posibilidad_ejercicio_por_gobierno_regional', models.TextField(blank=True, max_length=500)),
                ('organo_actual_competencia', models.TextField(blank=True, max_length=500)),
                ('formulario_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='formularios_sectoriales.formulariosectorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganigramaRegional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('documento', models.FileField(blank=True, null=True, upload_to='formulario_sectorial', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Organigrama Regional')),
                ('paso1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organigramaregional_set', to='formularios_sectoriales.paso1')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organigramas_regionales', to='regioncomuna.region')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarcoJuridico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('documento', models.FileField(blank=True, null=True, upload_to='formulario_sectorial', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Marco jurídico que lo rige')),
                ('paso1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcojuridico_set', to='formularios_sectoriales.paso1')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaso1',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('completada', models.BooleanField(default=False)),
                ('forma_juridica_organismo', models.TextField(blank=True, max_length=500)),
                ('descripcion_archivo_marco_juridico', models.TextField(blank=True, max_length=500)),
                ('mision_institucional', models.TextField(blank=True, max_length=500)),
                ('informacion_adicional_marco_juridico', models.TextField(blank=True, max_length=500)),
                ('organigrama_nacional', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Organigrama Nacional')),
                ('descripcion_archivo_organigrama_regional', models.TextField(blank=True, max_length=500)),
                ('identificacion_competencia', models.TextField(blank=True, max_length=500)),
                ('fuentes_normativas', models.TextField(blank=True, max_length=500)),
                ('territorio_competencia', models.TextField(blank=True, max_length=500)),
                ('enfoque_territorial_competencia', models.TextField(blank=True, max_length=500)),
                ('ambito', models.CharField(blank=True, choices=[('AP', 'Fomento de las Actividades Productivas'), ('OT', 'Ordenamiento Territorial'), ('DSC', 'Desarrollo Social y Cultural')], max_length=5)),
                ('posibilidad_ejercicio_por_gobierno_regional', models.TextField(blank=True, max_length=500)),
                ('organo_actual_competencia', models.TextField(blank=True, max_length=500)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('formulario_sectorial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paso1',
                'verbose_name_plural': 'historical paso1s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalOrganigramaRegional',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('documento', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Organigrama Regional')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paso1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.paso1')),
                ('region', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='regioncomuna.region')),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelo Bases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMarcoJuridico',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('documento', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Marco jurídico que lo rige')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paso1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.paso1')),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelo Bases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
