# Generated by Django 4.2.2 on 2023-12-12 12:15

import applications.base.functions
import applications.formularios_sectoriales.functions
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularios_sectoriales', '0006_paso1_organigramaregional_marcojuridico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaso1',
            old_name='completada',
            new_name='completado',
        ),
        migrations.RenameField(
            model_name='paso1',
            old_name='completada',
            new_name='completado',
        ),
        migrations.AlterField(
            model_name='organigramaregional',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=applications.formularios_sectoriales.functions.organigrama_regional_path, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Organigrama Regional'),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paso1', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.CreateModel(
            name='Paso3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('completado', models.BooleanField(default=False)),
                ('universo_cobertura', models.TextField(blank=True, max_length=800)),
                ('descripcion_cobertura', models.TextField(blank=True, max_length=800)),
                ('formulario_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paso3', to='formularios_sectoriales.formulariosectorial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaso3',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('completado', models.BooleanField(default=False)),
                ('universo_cobertura', models.TextField(blank=True, max_length=800)),
                ('descripcion_cobertura', models.TextField(blank=True, max_length=800)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('formulario_sectorial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paso3',
                'verbose_name_plural': 'historical paso3s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCoberturaAnual',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('anio', models.IntegerField()),
                ('universo_cobertura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cobertura_efectivamente_abordada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recursos_ejecutados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('formulario_sectorial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelo Bases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CoberturaAnual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('anio', models.IntegerField()),
                ('universo_cobertura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cobertura_efectivamente_abordada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recursos_ejecutados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formulario_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturaanual_set', to='formularios_sectoriales.formulariosectorial')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'abstract': False,
            },
        ),
    ]
