# Generated by Django 4.2.2 on 2023-12-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0009_historicalprocedimientosetapas_etapa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='capacitacion_plataforma',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='capacitacion_plataforma',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
