# Generated by Django 4.2.2 on 2023-12-14 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0011_alter_formulariosectorial_competencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapasejerciciocompetencia',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_2_3_etapas_ejercicio_competencia', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='flujogramacompetencia',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_2_5_flujograma_competencia', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='organismosintervinientes',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_2_1_organismos_intervinientes', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_2_4_plataformas_y_softwares', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='procedimientosetapas',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_etapas', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='unidadesintervinientes',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_2_2_unidades_intervinientes', to='formularios_sectoriales.formulariosectorial'),
        ),
    ]
