# Generated by Django 4.2.2 on 2023-12-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0012_alter_etapasejerciciocompetencia_formulario_sectorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmarcojuridico',
            name='paso1',
        ),
        migrations.RemoveField(
            model_name='historicalorganigramaregional',
            name='paso1',
        ),
        migrations.RemoveField(
            model_name='marcojuridico',
            name='paso1',
        ),
        migrations.RemoveField(
            model_name='organigramaregional',
            name='paso1',
        ),
        migrations.AddField(
            model_name='historicalmarcojuridico',
            name='formulario_sectorial',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AddField(
            model_name='historicalorganigramaregional',
            name='formulario_sectorial',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AddField(
            model_name='marcojuridico',
            name='formulario_sectorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='marcojuridico_set', to='formularios_sectoriales.formulariosectorial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organigramaregional',
            name='formulario_sectorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organigramaregional_set', to='formularios_sectoriales.formulariosectorial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paso2',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encabezado', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='procedimientosetapas',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='formularios_sectoriales.etapasejerciciocompetencia'),
        ),
    ]
