# Generated by Django 4.2.2 on 2023-12-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0013_remove_historicalmarcojuridico_paso1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso1',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formularios_sectoriales.formulariosectorial'),
        ),
    ]
