# Generated by Django 4.2.2 on 2023-12-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0016_costoanio_subtitulos_variacionpromedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coberturaanual',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobertura_anual', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='marcojuridico',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcojuridico', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='organigramaregional',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organigramaregional', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paso1', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='etapas',
            field=models.ManyToManyField(blank=True, related_name='PlataformasySoftwares_set', to='formularios_sectoriales.etapasejerciciocompetencia'),
        ),
    ]
