# Generated by Django 4.2.2 on 2023-12-19 20:54

from django.db import migrations, models
import django.db.models.deletion
import pandas as pd
from pathlib import Path


def populate_models_from_excel(apps, schema_editor):
    Subtitulos = apps.get_model('formularios_sectoriales', 'Subtitulos')
    ItemSubtitulo = apps.get_model('formularios_sectoriales', 'ItemSubtitulo')

    file_path = Path(__file__).resolve().parent.parent / 'Clasificador Presupuestario.xlsx'
    df = pd.read_excel(file_path, header=None)

    for column in df.columns:
        subtitulo_name = df.iloc[0, column]
        items = df.iloc[1:, column].dropna().tolist()

        subtitulo, created = Subtitulos.objects.get_or_create(subtitulo=subtitulo_name)

        for item in items:
            ItemSubtitulo.objects.get_or_create(
                item=item,
                subtitulo=subtitulo,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0018_asignar_subtitulos_desde_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimientosetapas',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.RunPython(populate_models_from_excel)
    ]
