# Generated by Django 4.2.2 on 2023-12-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0019_alter_procedimientosetapas_formulario_sectorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresumencostosporsubtitulo',
            name='formulario_sectorial',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AddField(
            model_name='resumencostosporsubtitulo',
            name='formulario_sectorial',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, related_name='p_5_1_c_resumen_costos_por_subtitulo', to='formularios_sectoriales.formulariosectorial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costosdirectos',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_5_1_a_costos_directos', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='costosindirectos',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_5_1_b_costos_indirectos', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='evoluciongastoasociado',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_5_2_evolucion_gasto_asociado', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AlterField(
            model_name='variacionpromedio',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_5_2_variacion_promedio', to='formularios_sectoriales.formulariosectorial'),
        ),
    ]
