# Generated by Django 4.2.2 on 2023-12-21 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0007_ambito_remove_competencia_ambito_and_more'),
        ('formularios_sectoriales', '0020_historicalresumencostosporsubtitulo_formulario_sectorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaso1',
            name='ambito',
        ),
        migrations.RemoveField(
            model_name='paso1',
            name='ambito',
        ),
        migrations.AddField(
            model_name='historicalpaso1',
            name='ambito_paso1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='competencias.ambito'),
        ),
        migrations.AddField(
            model_name='paso1',
            name='ambito_paso1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paso1', to='competencias.ambito'),
        ),
        migrations.AlterField(
            model_name='costosdirectos',
            name='etapa',
            field=models.ManyToManyField(blank=True, related_name='costos_directos', to='formularios_sectoriales.etapasejerciciocompetencia'),
        ),
    ]
