# Generated by Django 4.2.2 on 2023-12-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0021_remove_historicalpaso1_ambito_remove_paso1_ambito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evoluciongastoasociado',
            name='costo_anio',
        ),
        migrations.AddField(
            model_name='costoanio',
            name='evolucion_gasto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='costo_anio', to='formularios_sectoriales.evoluciongastoasociado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcostoanio',
            name='evolucion_gasto',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.evoluciongastoasociado'),
        ),
    ]
