# Generated by Django 4.2.2 on 2023-12-22 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def crear_calidad_juridica(apps, schema_editor):
    # Obtén el modelo CalidadJuridica
    CalidadJuridica = apps.get_model('formularios_sectoriales', 'CalidadJuridica')

    # Nombres de las calidades jurídicas a crear
    nombres_calidad_juridica = [
        'Planta',
        'Contrata',
        'Honorario asimilado a grado',
        'Honorario a suma alzada',
        'Comisión de servicio',
        'Otro'
    ]

    # Crea y guarda las instancias de CalidadJuridica
    for nombre in nombres_calidad_juridica:
        CalidadJuridica.objects.create(calidad_juridica=nombre)


def crear_estamento(apps, schema_editor):
    # Obtén el modelo Estamento
    Estamento = apps.get_model('formularios_sectoriales', 'Estamento')

    # Nombres de los estamentos a crear
    nombres_estamento = [
        'Directivo',
        'Profesional',
        'Técnico',
        'Administrativo',
        'Auxiliar',
        'Otro'
    ]

    # Crea y guarda las instancias de Estamento
    for nombre in nombres_estamento:
        Estamento.objects.create(estamento=nombre)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularios_sectoriales', '0022_remove_evoluciongastoasociado_costo_anio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad_juridica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='descripcion_funciones_personal_directo',
            field=models.TextField(blank=True, max_length=1100),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='descripcion_funciones_personal_indirecto',
            field=models.TextField(blank=True, max_length=1100),
        ),
        migrations.AddField(
            model_name='paso5',
            name='descripcion_funciones_personal_directo',
            field=models.TextField(blank=True, max_length=1100),
        ),
        migrations.AddField(
            model_name='paso5',
            name='descripcion_funciones_personal_indirecto',
            field=models.TextField(blank=True, max_length=1100),
        ),
        migrations.CreateModel(
            name='PersonalIndirecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('numero_personas', models.IntegerField(blank=True, null=True)),
                ('renta_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('calidad_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_indirecto', to='formularios_sectoriales.calidadjuridica')),
                ('estamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_indirecto', to='formularios_sectoriales.estamento')),
                ('formulario_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_5_3_b_personal_indirecto', to='formularios_sectoriales.formulariosectorial')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalDirecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('renta_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('calidad_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_directo', to='formularios_sectoriales.calidadjuridica')),
                ('estamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_directo', to='formularios_sectoriales.estamento')),
                ('formulario_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_5_3_a_personal_directo', to='formularios_sectoriales.formulariosectorial')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPersonalIndirecto',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('numero_personas', models.IntegerField(blank=True, null=True)),
                ('renta_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('calidad_juridica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.calidadjuridica')),
                ('estamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.estamento')),
                ('formulario_sectorial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelo Bases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPersonalDirecto',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('renta_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('calidad_juridica', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.calidadjuridica')),
                ('estamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.estamento')),
                ('formulario_sectorial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelo Bases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(crear_calidad_juridica, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(crear_estamento, reverse_code=migrations.RunPython.noop),

    ]
