# Generated by Django 4.2.2 on 2023-12-27 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0009_alter_competencia_ambito_competencia'),
        ('formularios_sectoriales', '0024_formulariosectorial_intento_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosectorial',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario_sectorial', to='competencias.competencia'),
        ),
    ]
