# Generated by Django 4.2.2 on 2023-12-28 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0025_alter_formulariosectorial_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso1',
            name='formulario_sectorial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paso1', to='formularios_sectoriales.formulariosectorial'),
        ),
    ]
