# Generated by Django 4.2.2 on 2023-12-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0028_observacionessubdereformulariosectorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobservacionessubdereformulariosectorial',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalobservacionessubdereformulariosectorial',
            name='observacion_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observacionessubdereformulariosectorial',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacionessubdereformulariosectorial',
            name='observacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
