# Generated by Django 4.2.2 on 2024-01-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0029_historicalobservacionessubdereformulariosectorial_fecha_envio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorganismosintervinientes',
            old_name='sector_ministerio_servicio',
            new_name='nombre_ministerio_servicio',
        ),
        migrations.RenameField(
            model_name='organismosintervinientes',
            old_name='sector_ministerio_servicio',
            new_name='nombre_ministerio_servicio',
        ),
    ]
