# Generated by Django 4.2.2 on 2024-01-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0030_rename_sector_ministerio_servicio_historicalorganismosintervinientes_nombre_ministerio_servicio_and_'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorganismosintervinientes',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organismos intervinientes', 'verbose_name_plural': 'historical organismos intervinientess'},
        ),
        migrations.AlterModelOptions(
            name='historicalunidadesintervinientes',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical unidades intervinientes', 'verbose_name_plural': 'historical unidades intervinientess'},
        ),
        migrations.AlterModelOptions(
            name='organismosintervinientes',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='unidadesintervinientes',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='historicalpaso1',
            name='descripcion_archivo_organigrama_nacional',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='paso1',
            name='descripcion_archivo_organigrama_nacional',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='unidadesintervinientes',
            name='organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidadesintervinientes', to='formularios_sectoriales.organismosintervinientes'),
        ),
    ]
