# Generated by Django 4.2.2 on 2024-02-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0032_alter_coberturaanual_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapasejerciciocompetencia',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='historicaletapasejerciciocompetencia',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical etapas ejercicio competencia', 'verbose_name_plural': 'historical etapas ejercicio competencias'},
        ),
        migrations.AlterModelOptions(
            name='historicalplataformasysoftwares',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical plataformasy softwares', 'verbose_name_plural': 'historical plataformasy softwaress'},
        ),
        migrations.AlterModelOptions(
            name='historicalprocedimientosetapas',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical procedimientos etapas', 'verbose_name_plural': 'historical procedimientos etapass'},
        ),
        migrations.AlterModelOptions(
            name='plataformasysoftwares',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='procedimientosetapas',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='capacitacion_plataforma',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='costo_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='costo_mantencion_anual',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='capacitacion_plataforma',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='costo_adquisicion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='costo_mantencion_anual',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
