# Generated by Django 4.2.2 on 2024-02-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0033_alter_etapasejerciciocompetencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosdirectos',
            name='item_subtitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_directos', to='formularios_sectoriales.itemsubtitulo'),
        ),
    ]
