# Generated by Django 4.2.2 on 2024-02-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0034_alter_costosdirectos_item_subtitulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calidadjuridica',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='costoanio',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='costosdirectos',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='costosindirectos',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='estamento',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='evoluciongastoasociado',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='historicalcostoanio',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical costo anio', 'verbose_name_plural': 'historical costo anios'},
        ),
        migrations.AlterModelOptions(
            name='historicalcostosdirectos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical costos directos', 'verbose_name_plural': 'historical costos directoss'},
        ),
        migrations.AlterModelOptions(
            name='historicalcostosindirectos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical costos indirectos', 'verbose_name_plural': 'historical costos indirectoss'},
        ),
        migrations.AlterModelOptions(
            name='historicalevoluciongastoasociado',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical evolucion gasto asociado', 'verbose_name_plural': 'historical evolucion gasto asociados'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersonaldirecto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical personal directo', 'verbose_name_plural': 'historical personal directos'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersonalindirecto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical personal indirecto', 'verbose_name_plural': 'historical personal indirectos'},
        ),
        migrations.AlterModelOptions(
            name='historicalresumencostosporsubtitulo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical resumen costos por subtitulo', 'verbose_name_plural': 'historical resumen costos por subtitulos'},
        ),
        migrations.AlterModelOptions(
            name='historicalvariacionpromedio',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical variacion promedio', 'verbose_name_plural': 'historical variacion promedios'},
        ),
        migrations.AlterModelOptions(
            name='personaldirecto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='personalindirecto',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='resumencostosporsubtitulo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='variacionpromedio',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='costosdirectos',
            name='es_transversal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='costosindirectos',
            name='es_transversal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcostosdirectos',
            name='es_transversal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcostosindirectos',
            name='es_transversal',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
