# Generated by Django 4.2.2 on 2024-02-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0035_alter_calidadjuridica_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaso5',
            name='descripcion_costos_totales',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='paso5',
            name='descripcion_costos_totales',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
