# Generated by Django 4.2.2 on 2024-02-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0036_historicalpaso5_descripcion_costos_totales_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costoanio',
            options={'ordering': ['anio']},
        ),
        migrations.AlterModelOptions(
            name='evoluciongastoasociado',
            options={'ordering': ['subtitulo']},
        ),
        migrations.AlterModelOptions(
            name='resumencostosporsubtitulo',
            options={'ordering': ['subtitulo']},
        ),
        migrations.AlterModelOptions(
            name='variacionpromedio',
            options={'ordering': ['subtitulo']},
        ),
        migrations.RemoveField(
            model_name='flujogramacompetencia',
            name='descripcion_cualitativa',
        ),
        migrations.RemoveField(
            model_name='historicalflujogramacompetencia',
            name='descripcion_cualitativa',
        ),
        migrations.AddField(
            model_name='historicalpaso2',
            name='descripcion_cualitativa',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='paso2',
            name='descripcion_cualitativa',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
