# Generated by Django 4.2.2 on 2024-02-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0038_alter_historicalpersonaldirecto_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvariacionpromedio',
            name='gasto_n_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalvariacionpromedio',
            name='gasto_n_3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalvariacionpromedio',
            name='gasto_n_4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacionpromedio',
            name='gasto_n_2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacionpromedio',
            name='gasto_n_3',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacionpromedio',
            name='gasto_n_4',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
