# Generated by Django 4.2.2 on 2024-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0039_historicalvariacionpromedio_gasto_n_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvariacionpromedio',
            old_name='gasto_n_1',
            new_name='variacion_gasto_n_1',
        ),
        migrations.RenameField(
            model_name='historicalvariacionpromedio',
            old_name='gasto_n_2',
            new_name='variacion_gasto_n_2',
        ),
        migrations.RenameField(
            model_name='historicalvariacionpromedio',
            old_name='gasto_n_3',
            new_name='variacion_gasto_n_3',
        ),
        migrations.RenameField(
            model_name='historicalvariacionpromedio',
            old_name='gasto_n_4',
            new_name='variacion_gasto_n_4',
        ),
        migrations.RenameField(
            model_name='variacionpromedio',
            old_name='gasto_n_1',
            new_name='variacion_gasto_n_1',
        ),
        migrations.RenameField(
            model_name='variacionpromedio',
            old_name='gasto_n_2',
            new_name='variacion_gasto_n_2',
        ),
        migrations.RenameField(
            model_name='variacionpromedio',
            old_name='gasto_n_3',
            new_name='variacion_gasto_n_3',
        ),
        migrations.RenameField(
            model_name='variacionpromedio',
            old_name='gasto_n_4',
            new_name='variacion_gasto_n_4',
        ),
        migrations.AddField(
            model_name='historicalvariacionpromedio',
            name='variacion_gasto_n_5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variacionpromedio',
            name='variacion_gasto_n_5',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
