# Generated by Django 4.2.2 on 2024-02-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0040_rename_gasto_n_1_historicalvariacionpromedio_variacion_gasto_n_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvariacionpromedio',
            name='gasto_n_5',
        ),
        migrations.RemoveField(
            model_name='historicalvariacionpromedio',
            name='variacion',
        ),
        migrations.RemoveField(
            model_name='historicalvariacionpromedio',
            name='variacion_gasto_n_1',
        ),
        migrations.RemoveField(
            model_name='variacionpromedio',
            name='gasto_n_5',
        ),
        migrations.RemoveField(
            model_name='variacionpromedio',
            name='variacion',
        ),
        migrations.RemoveField(
            model_name='variacionpromedio',
            name='variacion_gasto_n_1',
        ),
    ]
