# Generated by Django 4.2.2 on 2024-02-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0041_remove_historicalvariacionpromedio_gasto_n_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_personal_contrata_justificado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_personal_contrata_justificar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_personal_planta_justificado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_personal_planta_justificar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_resto_justificado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_resto_justificar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_total_personal_contrata',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_total_personal_planta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso5',
            name='sub21_total_resto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_personal_contrata_justificado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_personal_contrata_justificar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_personal_planta_justificado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_personal_planta_justificar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_resto_justificado',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_resto_justificar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_total_personal_contrata',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_total_personal_planta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paso5',
            name='sub21_total_resto',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
