# Generated by Django 4.2.2 on 2024-02-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0042_historicalpaso5_sub21_personal_contrata_justificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalindirecto',
            options={'ordering': ['calidad_juridica']},
        ),
        migrations.AlterField(
            model_name='personaldirecto',
            name='estamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_directo', to='formularios_sectoriales.estamento'),
        ),
        migrations.AlterField(
            model_name='personalindirecto',
            name='estamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_indirecto', to='formularios_sectoriales.estamento'),
        ),
    ]
