# Generated by Django 4.2.2 on 2024-02-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0043_alter_personalindirecto_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaso1',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='historicalpaso2',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='historicalpaso3',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='historicalpaso4',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='historicalpaso5',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='paso1',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='paso2',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='paso3',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='paso4',
            name='completado',
        ),
        migrations.RemoveField(
            model_name='paso5',
            name='completado',
        ),
    ]
