# Generated by Django 4.2.2 on 2024-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0044_remove_historicalpaso1_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonalindirecto',
            name='total_rentas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='personalindirecto',
            name='total_rentas',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
