# Generated by Django 4.2.2 on 2024-02-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0046_rename_sub21_resto_justificado_historicalpaso5_sub21_gastos_en_personal_justificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalindirecto',
            options={'ordering': ['id']},
        ),
    ]
