# Generated by Django 4.2.2 on 2024-03-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0050_alter_costosindirectos_item_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldirecto',
            name='calidad_juridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_directo', to='formularios_sectoriales.calidadjuridica'),
        ),
        migrations.AlterField(
            model_name='personalindirecto',
            name='calidad_juridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_indirecto', to='formularios_sectoriales.calidadjuridica'),
        ),
    ]
