# Generated by Django 4.2.2 on 2024-04-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0051_alter_personaldirecto_calidad_juridica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaso5',
            name='glosas_especificas',
            field=models.TextField(blank=True, max_length=1100),
        ),
        migrations.AlterField(
            model_name='paso5',
            name='glosas_especificas',
            field=models.TextField(blank=True, max_length=1100),
        ),
    ]
