# Generated by Django 4.2.2 on 2024-04-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0052_alter_historicalpaso5_glosas_especificas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindicadordesempeno',
            name='medios_calculo',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalpaso2',
            name='descripcion_cualitativa',
            field=models.TextField(blank=True, max_length=2200),
        ),
        migrations.AlterField(
            model_name='indicadordesempeno',
            name='medios_calculo',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='paso2',
            name='descripcion_cualitativa',
            field=models.TextField(blank=True, max_length=2200),
        ),
    ]
