# Generated by Django 4.2.2 on 2024-04-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0052_alter_historicalpaso5_glosas_especificas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosdirectos',
            name='subtitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_directos', to='formularios_sectoriales.subtitulos'),
        ),
        migrations.AddField(
            model_name='costosindirectos',
            name='subtitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_indirectos', to='formularios_sectoriales.subtitulos'),
        ),
        migrations.AddField(
            model_name='historicalcostosdirectos',
            name='subtitulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.subtitulos'),
        ),
        migrations.AddField(
            model_name='historicalcostosindirectos',
            name='subtitulo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.subtitulos'),
        ),
    ]
