# Generated by Django 4.2.2 on 2024-04-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0053_alter_historicalindicadordesempeno_medios_calculo_and_more'),
        ('formularios_sectoriales', '0053_costosdirectos_subtitulo_costosindirectos_subtitulo_and_more'),
    ]

    operations = [
    ]
