# Generated by Django 4.2.2 on 2024-04-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0054_merge_20240411_1750'),
        ('formularios_sectoriales', '0054_merge_20240411_1806'),
    ]

    operations = [
    ]
