# Generated by Django 4.2.2 on 2024-05-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0055_merge_20240411_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorganigramaregional',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organigrama regional', 'verbose_name_plural': 'historical organigrama regionals'},
        ),
        migrations.AlterModelOptions(
            name='organigramaregional',
            options={'ordering': ['region']},
        ),
    ]
