# Generated by Django 4.2.2 on 2024-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0057_formulariosectorial_antecedente_adicional_sectorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariosectorial',
            name='descripcion_antecedente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalformulariosectorial',
            name='descripcion_antecedente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
