# Generated by Django 4.2.2 on 2024-05-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0059_paso3encabezado_coberturaanual_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaso3encabezado',
            name='formulario_sectorial',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.formulariosectorial'),
        ),
        migrations.AddField(
            model_name='paso3encabezado',
            name='formulario_sectorial',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paso3encabezado', to='formularios_sectoriales.formulariosectorial'),
        ),
    ]
