# Generated by Django 4.2.2 on 2024-05-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0062_costosdirectos_region_costosindirectos_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso5',
            name='formulario_sectorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paso5', to='formularios_sectoriales.formulariosectorial'),
        ),
    ]
