# Generated by Django 4.2.2 on 2024-05-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0063_alter_paso5_formulario_sectorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaso1',
            name='descripcion_archivo_marco_juridico',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='descripcion_archivo_organigrama_nacional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='descripcion_archivo_organigrama_regional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='enfoque_territorial_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='forma_juridica_organismo',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='fuentes_normativas',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='identificacion_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='informacion_adicional_marco_juridico',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='mision_institucional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='organo_actual_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='posibilidad_ejercicio_por_gobierno_regional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='historicalpaso1',
            name='territorio_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='descripcion_archivo_marco_juridico',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='descripcion_archivo_organigrama_nacional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='descripcion_archivo_organigrama_regional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='enfoque_territorial_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='forma_juridica_organismo',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='fuentes_normativas',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='identificacion_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='informacion_adicional_marco_juridico',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='mision_institucional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='organo_actual_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='posibilidad_ejercicio_por_gobierno_regional',
            field=models.TextField(blank=True, max_length=9000),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='territorio_competencia',
            field=models.TextField(blank=True, max_length=9000),
        ),
    ]
