# Generated by Django 4.2.2 on 2024-06-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0064_alter_historicalpaso1_descripcion_archivo_marco_juridico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapasejerciciocompetencia',
            name='descripcion_etapa',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='etapasejerciciocompetencia',
            name='nombre_etapa',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicaletapasejerciciocompetencia',
            name='descripcion_etapa',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicaletapasejerciciocompetencia',
            name='nombre_etapa',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalorganismosintervinientes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalorganismosintervinientes',
            name='nombre_ministerio_servicio',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalpaso2',
            name='descripcion_cualitativa',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='descripcion_costos',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='descripcion_tecnica',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='funcion_plataforma',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalplataformasysoftwares',
            name='nombre_plataforma',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalprocedimientosetapas',
            name='descripcion_procedimiento',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalunidadesintervinientes',
            name='descripcion_unidad',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='historicalunidadesintervinientes',
            name='nombre_unidad',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='organismosintervinientes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='organismosintervinientes',
            name='nombre_ministerio_servicio',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='paso2',
            name='descripcion_cualitativa',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='descripcion_costos',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='descripcion_tecnica',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='funcion_plataforma',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='plataformasysoftwares',
            name='nombre_plataforma',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='procedimientosetapas',
            name='descripcion_procedimiento',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='unidadesintervinientes',
            name='descripcion_unidad',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='unidadesintervinientes',
            name='nombre_unidad',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
