# Generated by Django 4.2.2 on 2024-06-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0065_alter_etapasejerciciocompetencia_descripcion_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonaldirecto',
            name='costos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.costosdirectos'),
        ),
        migrations.AddField(
            model_name='historicalpersonalindirecto',
            name='costos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formularios_sectoriales.costosindirectos'),
        ),
        migrations.AddField(
            model_name='personaldirecto',
            name='costos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_directo', to='formularios_sectoriales.costosdirectos'),
        ),
        migrations.AddField(
            model_name='personalindirecto',
            name='costos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_indirecto', to='formularios_sectoriales.costosindirectos'),
        ),
    ]
