# Generated by Django 4.2.2 on 2024-07-08 11:59

import applications.base.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0068_alter_formulariosectorial_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobservacionessubdereformulariosectorial',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='observacionessubdereformulariosectorial',
            name='documento',
        ),
        migrations.AddField(
            model_name='formulariosectorial',
            name='antecedente_adicional_subdere',
            field=models.FileField(blank=True, null=True, upload_to='formulario_sectorial', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedente adicional Observación SUBDERE'),
        ),
        migrations.AddField(
            model_name='historicalformulariosectorial',
            name='antecedente_adicional_subdere',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedente adicional Observación SUBDERE'),
        ),
        migrations.AlterField(
            model_name='formulariosectorial',
            name='antecedente_adicional_sectorial',
            field=models.FileField(blank=True, null=True, upload_to='formulario_sectorial', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedente adicional formulario sectorial'),
        ),
        migrations.AlterField(
            model_name='historicalformulariosectorial',
            name='antecedente_adicional_sectorial',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedente adicional formulario sectorial'),
        ),
    ]
