# Generated by Django 4.2.2 on 2024-07-18 13:53

from django.db import migrations, models


def convert_grado_personaldirecto(apps, schema_editor):
    PersonalDirecto = apps.get_model('formularios_sectoriales', 'PersonalDirecto')
    for pd in PersonalDirecto.objects.all():
        pd.grado = str(pd.grado) if pd.grado is not None else None
        pd.save()


def convert_grado_personalindirecto(apps, schema_editor):
    PersonalIndirecto = apps.get_model('formularios_sectoriales', 'PersonalIndirecto')
    for pi in PersonalIndirecto.objects.all():
        pi.grado = str(pi.grado) if pi.grado is not None else None
        pi.save()


def convert_historical_grado_personaldirecto(apps, schema_editor):
    HistoricalPersonalDirecto = apps.get_model('formularios_sectoriales', 'HistoricalPersonalDirecto')
    for hpd in HistoricalPersonalDirecto.objects.all():
        hpd.grado = str(hpd.grado) if hpd.grado is not None else None
        hpd.save()


def convert_historical_grado_personalindirecto(apps, schema_editor):
    HistoricalPersonalIndirecto = apps.get_model('formularios_sectoriales', 'HistoricalPersonalIndirecto')
    for hpi in HistoricalPersonalIndirecto.objects.all():
        hpi.grado = str(hpi.grado) if hpi.grado is not None else None
        hpi.save()


class Migration(migrations.Migration):
    dependencies = [
        ('formularios_sectoriales', '0069_remove_historicalobservacionessubdereformulariosectorial_documento_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_grado_personaldirecto, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(convert_grado_personalindirecto, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(convert_historical_grado_personaldirecto, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(convert_historical_grado_personalindirecto, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicalpersonaldirecto',
            name='grado',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonalindirecto',
            name='grado',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personaldirecto',
            name='grado',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalindirecto',
            name='grado',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
