# Generated by Django 4.2.2 on 2023-12-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectores_gubernamentales', '0002_ministerio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorgubernamental',
            name='ministerio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='sectores_gubernamentales.ministerio'),
            preserve_default=False,
        ),
    ]
