# Generated by Django 4.2.2 on 2023-11-09 21:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectores_gubernamentales', '0001_initial'),
        ('regioncomuna', '0002_auto_20231103_1736'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompetencia',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(db_index=True, max_length=200)),
                ('ambito', models.CharField(choices=[('OP', 'Oficio Presidencial'), ('SG', 'Solicitud GORE')], default='AP', max_length=5)),
                ('origen', models.CharField(choices=[('OP', 'Oficio Presidencial'), ('SG', 'Solicitud GORE')], default='OP', max_length=5)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EP', 'En Proceso'), ('FIN', 'Cerrada'), ('SU', 'Sin usuarios')], default='SU', max_length=5)),
                ('plazo_formulario_sectorial', models.IntegerField(help_text='El plazo debe estar entre 15 y 30 días.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(30)])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo Base',
                'verbose_name_plural': 'historical Modelo Bases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ambito', models.CharField(choices=[('OP', 'Oficio Presidencial'), ('SG', 'Solicitud GORE')], default='AP', max_length=5)),
                ('origen', models.CharField(choices=[('OP', 'Oficio Presidencial'), ('SG', 'Solicitud GORE')], default='OP', max_length=5)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('EP', 'En Proceso'), ('FIN', 'Cerrada'), ('SU', 'Sin usuarios')], default='SU', max_length=5)),
                ('plazo_formulario_sectorial', models.IntegerField(help_text='El plazo debe estar entre 15 y 30 días.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(30)])),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencia_creada', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('regiones', models.ManyToManyField(to='regioncomuna.region', verbose_name='Regiones')),
                ('sectores', models.ManyToManyField(to='sectores_gubernamentales.sectorgubernamental', verbose_name='Sectores')),
                ('usuarios_dipres', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'DIPRES'}, related_name='competencias_dipres', to=settings.AUTH_USER_MODEL)),
                ('usuarios_gore', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name', 'GORE')), related_name='competencias_gore', to=settings.AUTH_USER_MODEL)),
                ('usuarios_sectoriales', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('groups__name', 'Usuario Sectorial')), related_name='competencias_sectoriales', to=settings.AUTH_USER_MODEL)),
                ('usuarios_subdere', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'SUBDERE'}, related_name='competencias_subdere', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'abstract': False,
            },
        ),
    ]
