# Generated by Django 4.2.2 on 2023-11-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competencia',
            options={'verbose_name': 'Competencia', 'verbose_name_plural': 'Competencias'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompetencia',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Competencia', 'verbose_name_plural': 'historical Competencias'},
        ),
        migrations.AlterField(
            model_name='competencia',
            name='ambito',
            field=models.CharField(choices=[('AP', 'Fomento de las Actividades Productivas'), ('OT', 'Ordenamiento Territorial'), ('DSC', 'Desarrollo Social y Cultural')], default='AP', max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalcompetencia',
            name='ambito',
            field=models.CharField(choices=[('AP', 'Fomento de las Actividades Productivas'), ('OT', 'Ordenamiento Territorial'), ('DSC', 'Desarrollo Social y Cultural')], default='AP', max_length=5),
        ),
    ]
