# Generated by Django 4.2.2 on 2023-11-13 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0002_alter_competencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='plazo_formulario_gore',
            field=models.IntegerField(default=15, help_text='El plazo debe estar entre 15 y 30 días.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(30)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='plazo_formulario_gore',
            field=models.IntegerField(default=15, help_text='El plazo debe estar entre 15 y 30 días.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(30)]),
            preserve_default=False,
        ),
    ]
