# Generated by Django 4.2.2 on 2023-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0003_competencia_plazo_formulario_gore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompetencia',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompetencia',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
