# Generated by Django 4.2.2 on 2023-12-21 13:23

from django.db import migrations


def crear_ambitos(apps, schema_editor):
    # Obtén el modelo Ambito
    Ambito = apps.get_model('competencias', 'Ambito')

    # Nombres de los ambitos a crear
    nombres_ambitos = [
        'Fomento de las Actividades Productivas',
        'Ordenamiento Territorial',
        'Desarrollo Social y Cultural'
    ]

    # Crea y guarda las instancias de Ambito
    for nombre in nombres_ambitos:
        Ambito.objects.create(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0007_ambito_remove_competencia_ambito_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_ambitos, reverse_code=migrations.RunPython.noop),
    ]
