# Generated by Django 4.2.2 on 2023-12-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0008_crear_ambitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='ambito_competencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambito_competencia', to='competencias.ambito'),
        ),
    ]
