# Generated by Django 4.2.2 on 2024-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0010_competencia_ambito_definitivo_competencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='condiciones_ejercicio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='implementacion_acompanamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='modalidad_ejercicio',
            field=models.CharField(blank=True, choices=[('Exclusiva', 'Exclusiva'), ('Compartida', 'Compartida')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='competencia',
            name='recursos_requeridos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='condiciones_ejercicio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='implementacion_acompanamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='modalidad_ejercicio',
            field=models.CharField(blank=True, choices=[('Exclusiva', 'Exclusiva'), ('Compartida', 'Compartida')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='recursos_requeridos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
