# Generated by Django 4.2.2 on 2024-03-19 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regioncomuna', '0002_auto_20231103_1736'),
        ('competencias', '0011_competencia_condiciones_ejercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgradualidad',
            name='region',
        ),
        migrations.RemoveField(
            model_name='historicaltemporalidad',
            name='region',
        ),
        migrations.AlterField(
            model_name='gradualidad',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradualidad', to='competencias.competencia'),
        ),
        migrations.RemoveField(
            model_name='gradualidad',
            name='region',
        ),
        migrations.AlterField(
            model_name='recomendacionesdesfavorables',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones_desfavorables', to='competencias.competencia'),
        ),
        migrations.AlterField(
            model_name='temporalidad',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporalidad', to='competencias.competencia'),
        ),
        migrations.RemoveField(
            model_name='temporalidad',
            name='region',
        ),
        migrations.AddField(
            model_name='gradualidad',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, related_name='regiones', to='regioncomuna.region'),
        ),
        migrations.AddField(
            model_name='temporalidad',
            name='region',
            field=models.ManyToManyField(blank=True, null=True, to='regioncomuna.region'),
        ),
    ]
