# Generated by Django 4.2.2 on 2024-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioncomuna', '0002_auto_20231103_1736'),
        ('competencias', '0014_paso2revisionfinalsubdere_paso1revisionfinalsubdere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='regiones_recomendadas',
            field=models.ManyToManyField(blank=True, related_name='regiones_recomendadas', to='regioncomuna.region', verbose_name='Regiones recomendadas'),
        ),
    ]
