# Generated by Django 4.2.2 on 2024-04-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0019_historicaltemporalidad_gradualidad_meses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalgradualidad',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='historicalgradualidad',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Gradualidad',
        ),
        migrations.DeleteModel(
            name='HistoricalGradualidad',
        ),
    ]
