# Generated by Django 4.2.2 on 2024-05-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0024_competencia_imprimir_formulario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecomendacionesdesfavorables',
            name='justificacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recomendacionesdesfavorables',
            name='justificacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
