# Generated by Django 4.2.2 on 2024-05-14 13:29

import applications.base.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0025_alter_historicalrecomendacionesdesfavorables_justificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoscomplementarios',
            name='antecedente_adicional_revision_subdere',
            field=models.FileField(blank=True, null=True, upload_to='documentos_competencias', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedentes adicionales revisión SUBDERE'),
        ),
        migrations.AddField(
            model_name='historicaldocumentoscomplementarios',
            name='antecedente_adicional_revision_subdere',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedentes adicionales revisión SUBDERE'),
        ),
    ]
