# Generated by Django 4.2.2 on 2024-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0027_remove_documentoscomplementarios_antecedente_adicional_revision_subdere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='descripcion_antecedente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompetencia',
            name='descripcion_antecedente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
