# Generated by Django 4.2.2 on 2024-05-15 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0030_rename_nombrecompetenciaagrupada_competenciaagrupada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciaagrupada',
            name='competencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias_agrupadas', to='competencias.competencia'),
        ),
    ]
