# Generated by Django 4.2.2 on 2024-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0031_alter_competenciaagrupada_competencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competenciaagrupada',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcompetenciaagrupada',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='competenciaagrupada',
            constraint=models.UniqueConstraint(fields=('nombre', 'competencias'), name='unique_nombre_competencias'),
        ),
    ]
