# Generated by Django 4.2.2 on 2023-11-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0004_alter_competencia_fecha_fin_and_more'),
        ('regioncomuna', '0002_auto_20231103_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioGORE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('formulario_enviado', models.BooleanField(default=False)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_gores', to='regioncomuna.region')),
            ],
        ),
    ]
