# Generated by Django 4.2.2 on 2023-11-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariogore',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
