# Generated by Django 4.2.2 on 2024-03-06 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularios_sectoriales', '0047_alter_personalindirecto_options'),
        ('sectores_gubernamentales', '0006_alter_sectorgubernamental_ministerio'),
        ('formularios_gores', '0006_alter_paso1_formulario_gore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoAnioGore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('anio', models.IntegerField()),
                ('costo', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('evolucion_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costo_anio_gore', to='formularios_gores.fluctuacionpresupuestaria')),
            ],
            options={
                'ordering': ['anio'],
            },
        ),
        migrations.RenameModel(
            old_name='CostosDirectos',
            new_name='CostosDirectosGore',
        ),
        migrations.RenameModel(
            old_name='CostosIndirectos',
            new_name='CostosIndirectosGore',
        ),
        migrations.RenameModel(
            old_name='HistoricalCostoAnio',
            new_name='HistoricalCostoAnioGore',
        ),
        migrations.RenameModel(
            old_name='HistoricalCostosIndirectos',
            new_name='HistoricalCostosDirectosGore',
        ),
        migrations.RenameModel(
            old_name='HistoricalCostosDirectos',
            new_name='HistoricalCostosIndirectosGore',
        ),
        migrations.RenameModel(
            old_name='HistoricalResumenCostos',
            new_name='HistoricalResumenCostosGore',
        ),
        migrations.RenameModel(
            old_name='ResumenCostos',
            new_name='ResumenCostosGore',
        ),
        migrations.AlterModelOptions(
            name='historicalcostoaniogore',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical costo anio gore', 'verbose_name_plural': 'historical costo anio gores'},
        ),
        migrations.AlterModelOptions(
            name='historicalcostosdirectosgore',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical costos directos gore', 'verbose_name_plural': 'historical costos directos gores'},
        ),
        migrations.AlterModelOptions(
            name='historicalcostosindirectosgore',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical costos indirectos gore', 'verbose_name_plural': 'historical costos indirectos gores'},
        ),
        migrations.DeleteModel(
            name='CostoAnio',
        ),
    ]
