# Generated by Django 4.2.2 on 2024-03-07 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sectores_gubernamentales', '0006_alter_sectorgubernamental_ministerio'),
        ('formularios_sectoriales', '0047_alter_personalindirecto_options'),
        ('formularios_gores', '0007_costoaniogore_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPersonalDirecto',
            new_name='HistoricalPersonalDirectoGORE',
        ),
        migrations.RenameModel(
            old_name='HistoricalPersonalIndirecto',
            new_name='HistoricalPersonalIndirectoGORE',
        ),
        migrations.RenameModel(
            old_name='PersonalDirecto',
            new_name='PersonalDirectoGORE',
        ),
        migrations.RenameModel(
            old_name='PersonalIndirecto',
            new_name='PersonalIndirectoGORE',
        ),
        migrations.AlterModelOptions(
            name='historicalpersonaldirectogore',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical personal directo gore', 'verbose_name_plural': 'historical personal directo gores'},
        ),
        migrations.AlterModelOptions(
            name='historicalpersonalindirectogore',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical personal indirecto gore', 'verbose_name_plural': 'historical personal indirecto gores'},
        ),
    ]
