# Generated by Django 4.2.2 on 2024-03-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0009_remove_historicalrecursoscomparados_subtitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecursosfisicosinfraestructura',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='historicalsistemasinformaticos',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='recursosfisicosinfraestructura',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='sistemasinformaticos',
            name='subtitulo',
        ),
    ]
