# Generated by Django 4.2.2 on 2024-03-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0010_remove_historicalrecursosfisicosinfraestructura_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonaldirectogore',
            name='comision_servicio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonalindirectogore',
            name='comision_servicio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personaldirectogore',
            name='comision_servicio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='personalindirectogore',
            name='comision_servicio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
