# Generated by Django 4.2.2 on 2024-03-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0049_alter_costosdirectos_options_and_more'),
        ('formularios_gores', '0011_alter_historicalpersonaldirectogore_comision_servicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costosdirectosgore',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='costosindirectosgore',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='historicalrecursoscomparados',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical recursos comparados', 'verbose_name_plural': 'historical recursos comparadoss'},
        ),
        migrations.AlterModelOptions(
            name='personaldirectogore',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='personalindirectogore',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='recursoscomparados',
            options={'ordering': ['sector', 'item_subtitulo__subtitulo', 'item_subtitulo']},
        ),
        migrations.AlterModelOptions(
            name='recursosfisicosinfraestructura',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='sistemasinformaticos',
            options={'ordering': ['created_date']},
        ),
        migrations.AlterField(
            model_name='costosdirectosgore',
            name='item_subtitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_directos_gore', to='formularios_sectoriales.itemsubtitulo'),
        ),
    ]
