# Generated by Django 4.2.2 on 2024-03-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0049_alter_costosdirectos_options_and_more'),
        ('formularios_gores', '0012_alter_costosdirectosgore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluctuacionpresupuestaria',
            name='subtitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fluctuacion_presupuestaria', to='formularios_sectoriales.subtitulos'),
        ),
    ]
