# Generated by Django 4.2.2 on 2024-03-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0049_alter_costosdirectos_options_and_more'),
        ('formularios_gores', '0013_alter_fluctuacionpresupuestaria_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costosindirectosgore',
            name='item_subtitulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costos_indirectos_gore', to='formularios_sectoriales.itemsubtitulo'),
        ),
    ]
