# Generated by Django 4.2.2 on 2024-03-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0015_alter_personaldirectogore_calidad_juridica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonaldirectogore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalpersonalindirectogore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personaldirectogore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personalindirectogore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
