# Generated by Django 4.2.2 on 2024-03-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0016_historicalpersonaldirectogore_id_sectorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_22_diferencia_sector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_22_justificados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_22_por_justificar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_29_diferencia_sector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_29_justificados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_29_por_justificar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_22_diferencia_sector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_22_justificados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_22_por_justificar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_29_diferencia_sector',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_29_justificados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_29_por_justificar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
