# Generated by Django 4.2.2 on 2024-03-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0017_historicalpaso3_subtitulo_22_diferencia_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_21_informados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_21_justificados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpaso3',
            name='subtitulo_21_por_justificar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_21_informados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_21_justificados_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paso3',
            name='subtitulo_21_por_justificar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
