# Generated by Django 4.2.2 on 2024-03-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0019_observacionessubdereformulariogore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariogore',
            name='intento_envio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalformulariogore',
            name='intento_envio',
            field=models.BooleanField(default=False),
        ),
    ]
