# Generated by Django 4.2.2 on 2024-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0020_formulariogore_intento_envio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpersonalindirectogore',
            old_name='numero_personas',
            new_name='numero_personas_sectorial',
        ),
        migrations.RenameField(
            model_name='personalindirectogore',
            old_name='numero_personas',
            new_name='numero_personas_sectorial',
        ),
        migrations.AddField(
            model_name='historicalpersonalindirectogore',
            name='numero_personas_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalindirectogore',
            name='numero_personas_gore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
