# Generated by Django 4.2.2 on 2024-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0021_rename_numero_personas_historicalpersonalindirectogore_numero_personas_sectorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costosdirectosgore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costosindirectosgore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcostosdirectosgore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcostosindirectosgore',
            name='id_sectorial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
