# Generated by Django 4.2.2 on 2024-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0023_formulariogore_antecedente_adicional_gore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariogore',
            name='descripcion_antecedente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalformulariogore',
            name='descripcion_antecedente',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
