# Generated by Django 4.2.2 on 2024-06-19 17:04

import applications.base.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0024_formulariogore_descripcion_antecedente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalobservacionessubdereformulariogore',
            name='descripcion_documento',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='historicalobservacionessubdereformulariogore',
            name='documento',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Documento observación'),
        ),
        migrations.AddField(
            model_name='observacionessubdereformulariogore',
            name='descripcion_documento',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='observacionessubdereformulariogore',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='formulario_gore', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Documento observación'),
        ),
    ]
