# Generated by Django 4.2.2 on 2024-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0025_historicalobservacionessubdereformulariogore_descripcion_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariogore',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalformulariogore',
            name='nombre',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
