# Generated by Django 4.2.2 on 2024-07-15 17:07

import applications.base.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_gores', '0026_alter_formulariogore_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalobservacionessubdereformulariogore',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='observacionessubdereformulariogore',
            name='documento',
        ),
        migrations.AddField(
            model_name='formulariogore',
            name='antecedente_adicional_subdere',
            field=models.FileField(blank=True, null=True, upload_to='formulario_gore', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedente adicional Observación SUBDERE'),
        ),
        migrations.AddField(
            model_name='historicalformulariogore',
            name='antecedente_adicional_subdere',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Antecedente adicional Observación SUBDERE'),
        ),
    ]
