# Generated by Django 4.2.2 on 2023-11-08 10:07

from django.db import migrations


# Creación de grupos de administración
def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='SUBDERE')
    Group.objects.get_or_create(name='DIPRES')
    Group.objects.get_or_create(name='Usuario Sectorial')
    Group.objects.get_or_create(name='GORE')
    Group.objects.get_or_create(name='Usuario Observador')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
