# Generated by Django 4.2.2 on 2023-11-09 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectores_gubernamentales', '0001_initial'),
        ('regioncomuna', '0002_auto_20231103_1736'),
        ('users', '0002_crear_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='perfil',
            field=models.CharField(choices=[('SUBDERE', 'SUBDERE'), ('DIPRES', 'DIPRES'), ('Usuario Sectorial', 'Usuario Sectorial'), ('GORE', 'GORE'), ('Usuario Observador', 'Usuario Observador')], default='Usuario Observador', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='regioncomuna.region'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sectores_gubernamentales.sectorgubernamental'),
        ),
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('SUBDERE', 'SUBDERE'), ('DIPRES', 'DIPRES'), ('Usuario Sectorial', 'Usuario Sectorial'), ('GORE', 'GORE'), ('Usuario Observador', 'Usuario Observador')], default='Usuario Observador', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regioncomuna.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sectores_gubernamentales.sectorgubernamental'),
        ),
    ]
