# Generated by Django 4.2.2 on 2023-11-03 20:36

from django.db import migrations


def cargar_datos_regioncomuna(apps, schema_editor):
    Region = apps.get_model('regioncomuna', 'Region')
    Comuna = apps.get_model('regioncomuna', 'Comuna')

    import json
    with open('regioncomuna.json', 'r', encoding='utf-8') as f:
        data = json.load(f)

        for region_data in data['regiones']:
            region, created = Region.objects.get_or_create(
                region=region_data['region'])
            for comuna_data in region_data['comunas']:
                Comuna.objects.create(comuna=comuna_data, region=region)


class Migration(migrations.Migration):

    dependencies = [
        ('regioncomuna', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_datos_regioncomuna),
    ]
