# Generated by Django 4.2.2 on 2023-11-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencias', '0002_alter_competencia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('plazo_dias', models.IntegerField(blank=True, null=True)),
                ('enviada', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('competencia_creada', models.BooleanField(default=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
