# Generated by Django 4.2.2 on 2023-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa1',
            name='usuarios_vinculados',
            field=models.BooleanField(default=False),
        ),
    ]
