# Generated by Django 4.2.2 on 2023-11-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0003_alter_etapa1_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa1',
            name='tiempo_transcurrido_registrado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
