# Generated by Django 4.2.2 on 2023-11-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0004_etapa1_tiempo_transcurrido_registrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa1',
            name='ultima_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa1',
            name='tiempo_transcurrido_registrado',
            field=models.IntegerField(default=0),
        ),
    ]
