# Generated by Django 4.2.2 on 2023-11-21 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competencias', '0004_alter_competencia_fecha_fin_and_more'),
        ('etapas', '0005_etapa1_ultima_finalizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa1',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etapa1',
            name='deleted_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='etapa1',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='etapa1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HistoricalEtapa1',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('estado', models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('plazo_dias', models.IntegerField(blank=True, null=True)),
                ('enviada', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('tiempo_transcurrido_registrado', models.IntegerField(default=0)),
                ('ultima_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('competencia_creada', models.BooleanField(default=True)),
                ('usuarios_vinculados', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('competencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='competencias.competencia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical etapa1',
                'verbose_name_plural': 'historical etapa1s',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
