# Generated by Django 4.2.2 on 2023-11-21 14:24

import applications.base.functions
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('competencias', '0004_alter_competencia_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etapas', '0006_etapa1_created_date_etapa1_deleted_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEtapa2',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('estado', models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('plazo_dias', models.IntegerField(blank=True, null=True)),
                ('enviada', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('tiempo_transcurrido_registrado', models.IntegerField(default=0)),
                ('ultima_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('usuarios_notificados', models.BooleanField(default=False)),
                ('formulario_completo', models.BooleanField(default=False)),
                ('comentario_observacion', models.TextField(blank=True, max_length=500)),
                ('archivo_observacion', models.CharField(max_length=100, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Archivo Observación')),
                ('observacion_enviada', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('competencia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='competencias.competencia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Etapa 2',
                'verbose_name_plural': 'historical Etapas 2',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Etapa2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('estado', models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('plazo_dias', models.IntegerField(blank=True, null=True)),
                ('enviada', models.BooleanField(default=False)),
                ('aprobada', models.BooleanField(default=False)),
                ('tiempo_transcurrido_registrado', models.IntegerField(default=0)),
                ('ultima_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('usuarios_notificados', models.BooleanField(default=False)),
                ('formulario_completo', models.BooleanField(default=False)),
                ('comentario_observacion', models.TextField(blank=True, max_length=500)),
                ('archivo_observacion', models.FileField(upload_to='observaciones', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Archivo Observación')),
                ('observacion_enviada', models.BooleanField(default=False)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencias.competencia')),
            ],
            options={
                'verbose_name': 'Etapa 2',
                'verbose_name_plural': 'Etapas 2',
            },
        ),
    ]
