# Generated by Django 4.2.2 on 2023-11-22 11:08

import applications.base.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0007_historicaletapa2_etapa2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa2',
            old_name='comentario_observacion',
            new_name='comentario_observacion_etapa2',
        ),
        migrations.RenameField(
            model_name='etapa2',
            old_name='observacion_enviada',
            new_name='observacion_etapa2_enviada',
        ),
        migrations.RenameField(
            model_name='historicaletapa2',
            old_name='comentario_observacion',
            new_name='comentario_observacion_etapa2',
        ),
        migrations.RenameField(
            model_name='historicaletapa2',
            old_name='observacion_enviada',
            new_name='observacion_etapa2_enviada',
        ),
        migrations.RemoveField(
            model_name='etapa2',
            name='archivo_observacion',
        ),
        migrations.RemoveField(
            model_name='historicaletapa2',
            name='archivo_observacion',
        ),
        migrations.AddField(
            model_name='etapa2',
            name='archivo_observacion_etapa2',
            field=models.FileField(blank=True, null=True, upload_to='observaciones_etapa2', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Archivo Observación Etapa 2'),
        ),
        migrations.AddField(
            model_name='historicaletapa2',
            name='archivo_observacion_etapa2',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Archivo Observación Etapa 2'),
        ),
    ]
