# Generated by Django 4.2.2 on 2023-11-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios_sectoriales', '0003_remove_formulariosectorial_etapa_and_more'),
        ('etapas', '0010_remove_etapa2_archivo_observacion_etapa2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservacionFormulario',
            new_name='ObservacionSectorial',
        ),
    ]
