# Generated by Django 4.2.2 on 2023-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0014_remove_etapa4_archivo_observacion_etapa4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa3',
            name='omitir_etapa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa3',
            name='omitir_etapa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etapa1',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='etapa2',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='etapa3',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='etapa4',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='etapa5',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaletapa1',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaletapa2',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaletapa3',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaletapa4',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaletapa5',
            name='estado',
            field=models.CharField(choices=[('finalizada', 'Finalizada'), ('en_estudio', 'En Estudio'), ('no_iniciada', 'Aún no puede comenzar'), ('en_revision', 'En revisión SUBDERE'), ('atrasada', 'Atrasada')], default='no_iniciada', max_length=50),
        ),
    ]
