# Generated by Django 4.2.2 on 2023-11-29 15:05

import applications.base.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0015_etapa3_omitir_etapa_historicaletapa3_omitir_etapa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa3',
            name='archivo_observacion_minuta_sectorial',
            field=models.FileField(blank=True, null=True, upload_to='observaciones_formularios', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Archivo de Observación'),
        ),
        migrations.AddField(
            model_name='etapa3',
            name='comentario_minuta_sectorial',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='etapa3',
            name='observacion_minuta_sectorial_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa3',
            name='archivo_observacion_minuta_sectorial',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Archivo de Observación'),
        ),
        migrations.AddField(
            model_name='historicaletapa3',
            name='comentario_minuta_sectorial',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='historicaletapa3',
            name='observacion_minuta_sectorial_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
