# Generated by Django 4.2.2 on 2023-11-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0016_etapa3_archivo_observacion_minuta_sectorial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa4',
            old_name='formulario_completo',
            new_name='formulario_gore_completo',
        ),
        migrations.RenameField(
            model_name='etapa4',
            old_name='usuarios_notificados',
            new_name='usuarios_gore_notificados',
        ),
        migrations.RenameField(
            model_name='historicaletapa4',
            old_name='formulario_completo',
            new_name='formulario_gore_completo',
        ),
        migrations.RenameField(
            model_name='historicaletapa4',
            old_name='usuarios_notificados',
            new_name='usuarios_gore_notificados',
        ),
    ]
