# Generated by Django 4.2.2 on 2023-12-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0019_alter_etapa1_estado_alter_etapa2_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa3',
            old_name='omitir_etapa',
            new_name='omitida',
        ),
        migrations.RenameField(
            model_name='historicaletapa3',
            old_name='omitir_etapa',
            new_name='omitida',
        ),
        migrations.AddField(
            model_name='etapa1',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etapa2',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etapa4',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etapa5',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa1',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa2',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa4',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa5',
            name='omitida',
            field=models.BooleanField(default=False),
        ),
    ]
