# Generated by Django 4.2.2 on 2024-01-02 12:14

import applications.base.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0022_remove_observacionsectorial_formulario_sectorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa1',
            name='oficio_origen',
            field=models.FileField(blank=True, null=True, upload_to='oficios_competencias', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='etapa2',
            name='oficio_origen',
            field=models.FileField(blank=True, null=True, upload_to='oficios_competencias', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='etapa3',
            name='oficio_origen',
            field=models.FileField(blank=True, null=True, upload_to='oficios_competencias', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='etapa4',
            name='oficio_origen',
            field=models.FileField(blank=True, null=True, upload_to='oficios_competencias', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='etapa5',
            name='oficio_origen',
            field=models.FileField(blank=True, null=True, upload_to='oficios_competencias', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='historicaletapa1',
            name='oficio_origen',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='historicaletapa2',
            name='oficio_origen',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='historicaletapa3',
            name='oficio_origen',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='historicaletapa4',
            name='oficio_origen',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
        migrations.AddField(
            model_name='historicaletapa5',
            name='oficio_origen',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.base.functions.validate_file_size_twenty], verbose_name='Oficio inicio etapa'),
        ),
    ]
