# Generated by Django 4.2.2 on 2024-01-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0023_etapa1_oficio_origen_etapa2_oficio_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa2',
            name='formulario_sectorial_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etapa2',
            name='observaciones_formulario_sectorial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaletapa2',
            name='formulario_sectorial_completo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa2',
            name='observaciones_formulario_sectorial',
            field=models.BooleanField(default=True),
        ),
    ]
