# Generated by Django 4.2.2 on 2024-01-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0024_etapa2_formulario_sectorial_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa2',
            name='formulario_sectorial_completo',
        ),
        migrations.RemoveField(
            model_name='etapa2',
            name='observaciones_formulario_sectorial',
        ),
        migrations.RemoveField(
            model_name='historicaletapa2',
            name='formulario_sectorial_completo',
        ),
        migrations.RemoveField(
            model_name='historicaletapa2',
            name='observaciones_formulario_sectorial',
        ),
    ]
