# Generated by Django 4.2.2 on 2024-04-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0026_alter_etapa1_omitida_alter_etapa2_omitida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa2',
            name='observaciones_completas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaletapa2',
            name='observaciones_completas',
            field=models.BooleanField(default=False),
        ),
    ]
