# Generated by Django 4.2.2 on 2024-07-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0027_etapa2_observaciones_completas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa3',
            name='archivo_observacion_minuta_sectorial',
        ),
        migrations.RemoveField(
            model_name='etapa3',
            name='comentario_minuta_etapa3',
        ),
        migrations.RemoveField(
            model_name='etapa5',
            name='archivo_observacion_minuta_gore',
        ),
        migrations.RemoveField(
            model_name='etapa5',
            name='comentario_minuta_etapa5',
        ),
        migrations.RemoveField(
            model_name='historicaletapa3',
            name='archivo_observacion_minuta_sectorial',
        ),
        migrations.RemoveField(
            model_name='historicaletapa3',
            name='comentario_minuta_etapa3',
        ),
        migrations.RemoveField(
            model_name='historicaletapa5',
            name='archivo_observacion_minuta_gore',
        ),
        migrations.RemoveField(
            model_name='historicaletapa5',
            name='comentario_minuta_etapa5',
        ),
    ]
