# Generated by Django 4.2.2 on 2024-07-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0028_remove_etapa3_archivo_observacion_minuta_sectorial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapa1',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='etapa2',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='etapa3',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='etapa4',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='etapa5',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='historicaletapa1',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='historicaletapa2',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='historicaletapa3',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='historicaletapa4',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RenameField(
            model_name='historicaletapa5',
            old_name='ultima_finalizacion',
            new_name='fecha_aprobada',
        ),
        migrations.RemoveField(
            model_name='etapa1',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='etapa2',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='etapa3',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='etapa4',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='etapa5',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='historicaletapa1',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='historicaletapa2',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='historicaletapa3',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='historicaletapa4',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.RemoveField(
            model_name='historicaletapa5',
            name='tiempo_transcurrido_registrado',
        ),
        migrations.AddField(
            model_name='etapa1',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa2',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa3',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa4',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapa5',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaletapa1',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaletapa2',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaletapa3',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaletapa4',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaletapa5',
            name='fecha_enviada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
